
services:

  pcstore_api:
    container_name: pcstore_api 
    build:
      context: .  
      dockerfile: Dockerfile.backend
    restart: always
    command: ["poetry", "run", "uvicorn", "main:app", "--host", "0.0.0.0", "--port", "8000"]
    env_file:
      - .env
    ports:
      - ${API_BASE_PORT}: 8000
