"""empty message

Revision ID: 6acd41cd350a
Revises: 1c5b63f0c030
Create Date: 2025-03-07 10:07:04.654384

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6acd41cd350a'
down_revision: Union[str, None] = '1c5b63f0c030'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('PC_Case_Specs', sa.Column('length', sa.Numeric(precision=10, scale=2), nullable=False))
    op.add_column('PC_Case_Specs', sa.Column('wigth', sa.Numeric(precision=10, scale=2), nullable=False))
    op.drop_column('PC_Case_Specs', 'weight')
    op.drop_column('PC_Case_Specs', 'wight')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('PC_Case_Specs', sa.Column('wight', sa.NUMERIC(precision=10, scale=2), autoincrement=False, nullable=False))
    op.add_column('PC_Case_Specs', sa.Column('weight', sa.NUMERIC(precision=10, scale=2), autoincrement=False, nullable=False))
    op.drop_column('PC_Case_Specs', 'wigth')
    op.drop_column('PC_Case_Specs', 'length')
    # ### end Alembic commands ###
