"""empty message

Revision ID: 78216a827a05
Revises: 52dc97b422d3
Create Date: 2025-01-12 16:05:58.827368

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '78216a827a05'
down_revision: Union[str, None] = '52dc97b422d3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Basket', sa.Column('products_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'Basket', 'Products', ['products_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'Basket', type_='foreignkey')
    op.drop_column('Basket', 'products_id')
    # ### end Alembic commands ###
