"""empty message

Revision ID: e0395abcb5ea
Revises: 2213042a49ca
Create Date: 2025-03-02 00:58:19.075786

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e0395abcb5ea'
down_revision: Union[str, None] = '2213042a49ca'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Power_Units', sa.Column('modular', sa.Boolean(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('Power_Units', 'modular')
    # ### end Alembic commands ###
