"""empty message

Revision ID: fdbd7a871899
Revises: ae363ab0a478
Create Date: 2025-03-02 16:24:47.153876

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fdbd7a871899'
down_revision: Union[str, None] = 'ae363ab0a478'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('Power_Units', 'cost',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('Power_Units', 'cost',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###
