"""empty message

Revision ID: 1c5b63f0c030
Revises: d54483cd48cd
Create Date: 2025-03-06 23:52:35.972911

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1c5b63f0c030'
down_revision: Union[str, None] = 'd54483cd48cd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Vents', sa.Column('specs_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'Vents', 'Vents_Specs', ['specs_id'], ['id'])
    op.drop_constraint('Vents_Specs_vent_id_fkey', 'Vents_Specs', type_='foreignkey')
    op.drop_column('Vents_Specs', 'vent_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Vents_Specs', sa.Column('vent_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.create_foreign_key('Vents_Specs_vent_id_fkey', 'Vents_Specs', 'Vents', ['vent_id'], ['id'])
    op.drop_constraint(None, 'Vents', type_='foreignkey')
    op.drop_column('Vents', 'specs_id')
    # ### end Alembic commands ###
