"""empty message

Revision ID: 41c62eaa1d5d
Revises: 6acd41cd350a
Create Date: 2025-03-07 10:33:38.675119

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '41c62eaa1d5d'
down_revision: Union[str, None] = '6acd41cd350a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('PC_Case_Specs', 'length',
               existing_type=sa.NUMERIC(precision=10, scale=2),
               type_=sa.Integer(),
               existing_nullable=False)
    op.alter_column('PC_Case_Specs', 'height',
               existing_type=sa.NUMERIC(precision=10, scale=2),
               type_=sa.Integer(),
               existing_nullable=False)
    op.alter_column('PC_Case_Specs', 'wigth',
               existing_type=sa.NUMERIC(precision=10, scale=2),
               type_=sa.Integer(),
               existing_nullable=False)
    op.drop_constraint('PC_Cases_form_factor_id_fkey', 'PC_Cases', type_='foreignkey')
    op.drop_column('PC_Cases', 'form_factor_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('PC_Cases', sa.Column('form_factor_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.create_foreign_key('PC_Cases_form_factor_id_fkey', 'PC_Cases', 'FormFactors', ['form_factor_id'], ['id'])
    op.alter_column('PC_Case_Specs', 'wigth',
               existing_type=sa.Integer(),
               type_=sa.NUMERIC(precision=10, scale=2),
               existing_nullable=False)
    op.alter_column('PC_Case_Specs', 'height',
               existing_type=sa.Integer(),
               type_=sa.NUMERIC(precision=10, scale=2),
               existing_nullable=False)
    op.alter_column('PC_Case_Specs', 'length',
               existing_type=sa.Integer(),
               type_=sa.NUMERIC(precision=10, scale=2),
               existing_nullable=False)
    # ### end Alembic commands ###
