"""empty message

Revision ID: 73803372c516
Revises: 8782f099951e
Create Date: 2025-03-02 00:39:20.036738

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '73803372c516'
down_revision: Union[str, None] = '8782f099951e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('RAM_Specs', sa.Column('ram_quantity', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'RAM_Specs', 'RAM_Quantities', ['ram_quantity'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'RAM_Specs', type_='foreignkey')
    op.drop_column('RAM_Specs', 'ram_quantity')
    # ### end Alembic commands ###
