"""empty message

Revision ID: e77a859696a7
Revises: fdbd7a871899
Create Date: 2025-03-03 16:24:28.089474

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e77a859696a7'
down_revision: Union[str, None] = 'fdbd7a871899'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('HDD_Specs', 'frequency')
    op.drop_column('M2_SSD_Specs', 'frequency')
    op.drop_column('SSD_Specs', 'frequency')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('SSD_Specs', sa.Column('frequency', sa.INTEGER(), autoincrement=False, nullable=False))
    op.add_column('M2_SSD_Specs', sa.Column('frequency', sa.INTEGER(), autoincrement=False, nullable=False))
    op.add_column('HDD_Specs', sa.Column('frequency', sa.INTEGER(), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
