"""empty message

Revision ID: e918ad7066df
Revises: 78216a827a05
Create Date: 2025-01-12 16:07:56.497519

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e918ad7066df'
down_revision: Union[str, None] = '78216a827a05'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('Basket', 'products_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('Basket', 'products_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###
